### ISSUE TITLE
Update to React 16?

### ISSUE THREAD

**Issue by Tuizi** [airtoxin/react-showcase#3]
Can you update this package to React 16?
The main issue is about PropTypes, with React 16 you should not use `React.PropTypes.object` but instead `import PropTypes from 'prop-types';` and then `PropTypes.object`

**Comment by airtoxin** [comment]
Oh, sorry for my lazy updating.
I'll try anytime soon.

**Comment by airtoxin** [comment]
Done https://github.com/airtoxin/react-showcase/pull/4.
Please try version 0.2.0
